/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_rit_se_beepbrake_MainActivity */

#ifndef _Included_edu_rit_se_beepbrake_MainActivity
#define _Included_edu_rit_se_beepbrake_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_rit_se_beepbrake_MainActivity
 * Method:    changeText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_rit_se_beepbrake_MainActivity_changeText
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
